### ISSUE TITLE
python3 readiness

### ISSUE THREAD

**Issue by djgalloway** [alfredodeza/prado#26]
Currently if I try to have a CentOS8 ephemeral slave curl the setup script from prado (even with a symlink from `/usr/bin/python` to `/usr/bin/python3`), the playbook fails:

```
[   67.169869] cloud-init[1814]: --> do not requiretty for sudoers
[   67.172775] cloud-init[1814]: --> getting ready to fetch ansible
[   93.910266] cloud-init[1814]: tar: main.yml: time stamp 2019-12-19 15:41:30 is 226.855353188 s in the future
[   94.057665] cloud-init[1814]: Traceback (most recent call last):
[   94.057916] cloud-init[1814]:   File "/prado_1576787836/playbook/../build/bin/../ansible/bin/ansible-playbook", line 60, in <module>
[   94.058450] cloud-init[1814]:     import ansible.constants as C
[   94.058986] cloud-init[1814]:   File "/prado_1576787836/build/ansible/lib/ansible/constants.py", line 19, in <module>
[   94.059511] cloud-init[1814]:     from ansible.config.manager import ConfigManager, ensure_type, get_ini_config_value
[   94.060358] cloud-init[1814]:   File "/prado_1576787836/build/ansible/lib/ansible/config/manager.py", line 17, in <module>
[   94.060892] cloud-init[1814]:     from yaml import load as yaml_load
[   94.061492] cloud-init[1814]:   File "/prado_1576787836/build/ansible/lib/yaml/__init__.py", line 2, in <module>
[   94.062070] cloud-init[1814]:     from error import *
[   94.062583] cloud-init[1814]: ModuleNotFoundError: No module named 'error'
ci-info: ++++++++Authorized keys from /home/cloud-user/.ssh/authorized_keys for user cloud-user+++++++++
```

**Comment by djgalloway** [comment]
Same error with updated pyyaml:

```
[   70.143212] cloud-init[1752]: --> do not requiretty for sudoers
[   70.148266] cloud-init[1752]: --> getting ready to fetch ansible
[   95.399360] cloud-init[1752]: tar: main.yml: time stamp 2019-12-19 16:28:28 is 225.681391464 s in the future
[   95.697222] cloud-init[1752]: Traceback (most recent call last):
[   95.697564] cloud-init[1752]:   File "/prado_1576790657/playbook/../build/bin/../ansible/bin/ansible-playbook", line 60, in <module>
[   95.698732] cloud-init[1752]:     import ansible.constants as C
[   95.699087] cloud-init[1752]:   File "/prado_1576790657/build/ansible/lib/ansible/constants.py", line 19, in <module>
[   95.699622] cloud-init[1752]:     from ansible.config.manager import ConfigManager, ensure_type, get_ini_config_value
[   95.700763] cloud-init[1752]:   File "/prado_1576790657/build/ansible/lib/ansible/config/manager.py", line 17, in <module>
[   95.701894] cloud-init[1752]:     from yaml import load as yaml_load
[   95.703050] cloud-init[1752]:   File "/prado_1576790657/build/ansible/lib/yaml/__init__.py", line 2, in <module>
[   95.704668] cloud-init[1752]:     from error import *
[   95.705390] cloud-init[1752]: ModuleNotFoundError: No module named 'error'
```

I ssh'ed to the node

```
[root@centos8-huge--9ae20883-6c60-4a19-9796-27eff5da016d ~]# cd /prado_1576790657/build
[root@centos8-huge--9ae20883-6c60-4a19-9796-27eff5da016d build]#  ll sources/
total 15140
drwxr-xr-x. 11 cloud-user cloud-user     4096 Jul 25 14:16 ansible-2.8.3
-rw-rw-r--.  1 cloud-user cloud-user 14343746 Dec 19 16:00 ansible.tar.gz
drwxr-xr-x.  8 cloud-user cloud-user      264 Jun  6  2014 Jinja2-2.7.3
-rw-rw-r--.  1 cloud-user cloud-user   378470 Dec 19 16:00 jinja2.tar.gz
drwxr-xr-x.  4 cloud-user cloud-user      167 May  8  2014 MarkupSafe-0.23
-rw-rw-r--.  1 cloud-user cloud-user    13416 Dec 19 16:00 markupsafe.tar.gz
drwxr-xr-x.  6 cloud-user cloud-user      236 Oct 14  2013 pycrypto-2.6.1
-rw-rw-r--.  1 cloud-user cloud-user   446240 Dec 19 16:00 pycrypto.tar.gz
drwxrwsr-x.  7 cloud-user cloud-user      162 Jun  6  2019 PyYAML-5.1.1
-rw-rw-r--.  1 cloud-user cloud-user   274442 Dec 19 16:00 pyyaml.tar.gz
drwxr-xr-x.  4 cloud-user cloud-user      192 Jan  2  2015 six-1.9.0
-rw-rw-r--.  1 cloud-user cloud-user    29127 Dec 19 16:00 six.tar.gz
```
